markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: writelife.github.io
title: Writelife’s Blog
description: iOS, C, C++, OC, reading...
author: Adair Teng
email: 95681120@qq.com
github: writelife

config:
  js_dir:
  img_dir:
  css_dir: